# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Master's Fellowship
email: your-email@domain.com
description: The Master’s Fellowship is an association of churches and church leaders affiliated with the ministries of John
  MacArthur. Our desire is to network like-minded pastors and churches who are faithful to the inerrant truth of biblical doctrine. The purpose of this network is to facilitate the mission of The Master’s University and Seminary in training up the next generation of pastors, teachers and faithful church members to know and serve the Lord Jesus Christ.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://themastersfellowship.org
twitter_username: jekyllrb
github_username:  jekyll
google_analytics: UA-92750701-1

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
