# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Master's Fellowship
name: The Master's Fellowship
email: tmf@masters.edu
description: The Master’s Fellowship is an association of pastors and missionaries bound together by love for the Living Word, The Master, our Lord Jesus, the church for which He died, and the bold proclamation of the exposited written word. The Fellowship’s purpose is to support the mission and leadership of the local church by connecting and networking like-minded pastors and missionaries who share core biblical convictions of doctrine and praxis.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://themastersfellowship.org
twitter_username: jekyllrb
github_username:  jekyll
google_analytics: UA-92750701-1
maps:
  google:
    api_key: AIzaSyAwy6PKU4r7ICmQVsW-e0Pu0-tA9b9MpGM

# Build settings
markdown: kramdown
theme: minima
sass:
  style: compressed
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-feed
breadcrumbs: true
